name: Build and Push Docker Image for Nod (Manual)

on:
  workflow_dispatch:  # Trigger on manual workflow dispatch
    inputs:
        applicationrepo:
          description: 'Name of the react application repo'  # What's this input for?
          required: true  # Is it optional or required?
        branchOrTagName:
          description: 'Name of the branch to checkout'
          required: true
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Show repository URL
        run: echo ${{ inputs.application-repo }}:${{ inputs.branchOrTagName }}
        
      - name: Checkout React App Repository
        uses: actions/checkout@v3
        
        with:
          repository: ${{ inputs.applicationrepo }}
          ref: ${{ inputs.branchOrTagName }}
          token: ${{ secrets.backstage_token }}
        
        #at: ${{ inputs.react_app_repo }}  # Use input for URL

      - name: Use Node.js 20  # Adjust the version as needed
        uses: actions/setup-node@v3
        with:
          node-version: 20.13.1

      #- name: Install dependencies
      #  run: npm install

      - name: Build Docker image
        run: docker build -t rohit051989/backstage-react-app-with-ts:latest .  # Replace placeholders

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push rohit051989/backstage-react-app-with-ts:latest  # Replace placeholders
